# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZA6WF9fII-I2X0IeIgYyK_zzJZ514CL
"""

!pip install xgboost

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from xgboost import XGBClassifier
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("heart.csv")  # Replace with your file name
df.head()

X = df.drop("target", axis=1)
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = XGBClassifier(
    n_estimators=500,
    max_depth=5,
    learning_rate=0.03,
    subsample=1,
    colsample_bytree=1,
    use_label_encoder=False,
    eval_metric='logloss',
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("✅ Accuracy:", round(accuracy * 100, 2), "%")

import seaborn as sns
print("\n📄 Classification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""The previous cell failed because `X_train` and `y_train` were not defined. This can happen if the runtime is reset or if the cells that define these variables are not executed before the grid search cell.

To resolve this, ensure that the cells for splitting the data (`H2-56E7kfn1S`) and scaling the features (`bAiLmLaDfqud`) are executed before running the grid search. I'll rerun those cells now, and then execute the grid search cell again.
"""

from sklearn.model_selection import RandomizedSearchCV
from xgboost import XGBClassifier
import numpy as np

# Define base model
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)

# Define parameter grid (same as before)
param_grid = {
    'n_estimators': [100, 300, 500],
    'max_depth': [3, 5, 6],
    'learning_rate': [0.01, 0.03, 0.1],
    'subsample': [0.8, 1.0],
    'colsample_bytree': [0.8, 1.0]
}

# RandomizedSearchCV (tries only a limited number of random combinations)
random_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_grid,
    n_iter=20,             # only test 20 random combinations instead of 108
    scoring='accuracy',
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

# Fit on training data
random_search.fit(X_train, y_train)

# Show best parameters
print("✅ Best Parameters:", random_search.best_params_)
print("✅ Best CV Score:", round(random_search.best_score_ * 100, 2), "%")

# Evaluate best model on test set
best_model = random_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\n📄 Test Accuracy:", round(accuracy_score(y_test, y_pred) * 100, 2), "%")
print("\n📄 Classification Report:\n", classification_report(y_test, y_pred))

# Imports
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# Define models
models = {
    "XGBoost": XGBClassifier(
        n_estimators=500, max_depth=5, learning_rate=0.03,
        subsample=1.0, colsample_bytree=1.0, eval_metric='logloss', random_state=42
    ),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "SVM": SVC(kernel="rbf", probability=True, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier(n_neighbors=5)
}

# Dictionary to store results
results = {}

# Train and evaluate each model
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    results[name] = acc

    print(f"\n✅ {name} Accuracy: {round(acc*100,2)} %")
    print(classification_report(y_test, y_pred))

# Convert results to DataFrame for comparison
results_df = pd.DataFrame(list(results.items()), columns=["Model", "Accuracy"])

# Show comparison table
print("\n📊 Model Comparison:\n")
print(results_df)

# Plot comparison
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.bar(results_df["Model"], results_df["Accuracy"], color="skyblue")
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.ylim(0.8, 1.0)
plt.show()

from sklearn.metrics import roc_curve, roc_auc_score
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

for name, model in models.items():
    # Predict probabilities
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
    else:
        # Some models (like SVM without probability=True) don't support predict_proba
        # But we already set probability=True for SVM, so this should not trigger
        y_proba = model.decision_function(X_test)

    # Compute ROC curve and AUC
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    auc = roc_auc_score(y_test, y_proba)

    # Plot ROC curve
    plt.plot(fpr, tpr, label=f"{name} (AUC = {auc:.2f})")

# Random guessing line
plt.plot([0,1],[0,1],'k--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend(loc="lower right")
plt.show()

from sklearn.metrics import roc_auc_score

# Collect performance metrics
performance = []

for name, model in models.items():
    # Predictions
    y_pred = model.predict(X_test)

    # Probabilities for AUC
    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)[:, 1]
    else:
        y_proba = model.decision_function(X_test)

    # Metrics
    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_proba)

    performance.append([name, round(acc*100, 2), round(auc, 3)])

# Create DataFrame
perf_df = pd.DataFrame(performance, columns=["Model", "Accuracy (%)", "AUC"])

print("\n📊 Model Performance Table:\n")
print(perf_df)

# Display nicely
import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.table(cellText=perf_df.values, colLabels=perf_df.columns, cellLoc="center", loc="center")
plt.axis("off")
plt.title("Performance Comparison of Models")
plt.show()

from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

# Define parameter grids for each model
param_grids = {
    "XGBoost": {
        "n_estimators": [100, 300, 500],
        "max_depth": [3, 5, 6],
        "learning_rate": [0.01, 0.03, 0.1],
        "subsample": [0.8, 1.0],
        "colsample_bytree": [0.8, 1.0]
    },
    "Random Forest": {
        "n_estimators": [100, 200, 500],
        "max_depth": [5, 10, None],
        "criterion": ["gini", "entropy"]
    },
    "SVM": {
        "C": [0.1, 1, 10],
        "gamma": ["scale", "auto"],
        "kernel": ["linear", "rbf"]
    },
    "Decision Tree": {
        "max_depth": [3, 5, 10, None],
        "criterion": ["gini", "entropy"]
    },
    "KNN": {
        "n_neighbors": [3, 5, 7, 9],
        "weights": ["uniform", "distance"],
        "metric": ["euclidean", "manhattan"]
    }
}

# Models
base_models = {
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "SVM": SVC(probability=True, random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "KNN": KNeighborsClassifier()
}

best_models = {}
performance = []
conf_matrices = {}

# Loop through models
for name, model in base_models.items():
    print(f"\n🔎 Tuning {name} ...")
    search = RandomizedSearchCV(
        estimator=model,
        param_distributions=param_grids[name],
        n_iter=10,  # fewer iterations for speed
        cv=5,
        scoring='accuracy',
        n_jobs=-1,
        random_state=42,
        verbose=1
    )

    search.fit(X_train, y_train)
    best_models[name] = search.best_estimator_

    print(f"✅ Best Params for {name}: {search.best_params_}")
    y_pred = search.best_estimator_.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, search.best_estimator_.predict_proba(X_test)[:,1])

    performance.append([name, round(acc*100, 2), round(auc, 3)])
    conf_matrices[name] = confusion_matrix(y_test, y_pred)

# Final performance table
perf_df = pd.DataFrame(performance, columns=["Model", "Accuracy (%)", "AUC"])
print("\n📊 Final Performance:\n")
print(perf_df)

import matplotlib.pyplot as plt

# Models
models = ["XGBoost", "Random Forest", "SVM", "Decision Tree", "KNN"]

# Accuracy values
accuracy = [98.54, 98.54, 88.78, 98.54, 83.41]

# Plot Accuracy
plt.figure(figsize=(7,5))
bars = plt.bar(models, accuracy, color="royalblue", width=0.6)

# Add value labels on top of bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.3, f"{yval:.2f}%",
             ha='center', va='bottom', fontsize=10, fontweight="bold")

plt.title("Model Accuracy", fontsize=14, fontweight="bold")
plt.ylabel("Accuracy (%)", fontsize=12)
plt.ylim(75, 102)
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.show()

import matplotlib.pyplot as plt

# Models
models = ["XGBoost", "Random Forest", "SVM", "Decision Tree", "KNN"]

# F1-Score values
f1_scores = [0.99, 0.99, 0.89, 0.99, 0.83]

# Convert to percentage for plotting
f1_percent = [x * 100 for x in f1_scores]

# Plot F1-Score
plt.figure(figsize=(7,5))
bars = plt.bar(models, f1_percent, color="orange", width=0.6)

# Add value labels on top
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.3, f"{yval:.2f}%",
             ha='center', va='bottom', fontsize=10, fontweight="bold")

plt.title("Model F1-Score", fontsize=14, fontweight="bold")
plt.ylabel("F1-Score (%)", fontsize=12)
plt.ylim(70, 102)
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.show()

import matplotlib.pyplot as plt

# Models
models = ["XGBoost", "Random Forest", "SVM", "Decision Tree", "KNN"]

# Precision values
precision_scores = [0.99, 0.99, 0.93, 0.99, 0.84]

# Convert to percentage
precision_percent = [x * 100 for x in precision_scores]

# Plot Precision
plt.figure(figsize=(7,5))
bars = plt.bar(models, precision_percent, color="green", width=0.6)

# Add value labels on top
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.3, f"{yval:.2f}%",
             ha='center', va='bottom', fontsize=10, fontweight="bold")

plt.title("Model Precision", fontsize=14, fontweight="bold")
plt.ylabel("Precision (%)", fontsize=12)
plt.ylim(70, 102)
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.show()

# Recall values
recall_scores = [0.99, 0.99, 0.83, 0.99, 0.83]

# Convert to percentage
recall_percent = [x * 100 for x in recall_scores]

# Plot Recall
plt.figure(figsize=(7,5))
bars = plt.bar(models, recall_percent, color="red", width=0.6)

# Add value labels on top
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.3, f"{yval:.2f}%",
             ha='center', va='bottom', fontsize=10, fontweight="bold")

plt.title("Model Recall", fontsize=14, fontweight="bold")
plt.ylabel("Recall (%)", fontsize=12)
plt.ylim(70, 102)
plt.grid(axis="y", linestyle="--", alpha=0.6)

plt.show()

import matplotlib.pyplot as plt

# ROC-AUC values (from your results)
auc_scores = {
    'XGBoost': 0.992,
    'Random Forest': 0.991,
    'SVM': 0.827,
    'Decision Tree': 0.991,
    'KNN': 0.804
}

# Convert to percentage
models = list(auc_scores.keys())
values = [v * 100 for v in auc_scores.values()]

# Plot AUC
plt.figure(figsize=(7,5))
bars = plt.bar(models, values, color='purple', width=0.6)

# Add value labels on top of bars
for bar, val in zip(bars, values):
    plt.text(bar.get_x() + bar.get_width()/2, val + 0.3,
             f"{val:.2f}%", ha='center', va='bottom',
             fontsize=10, fontweight='bold')

plt.ylim(40, 102)   # y-axis starts from 0.4 (40%) up to 100%
plt.title("Model ROC-AUC Comparison", fontsize=14, fontweight='bold')
plt.ylabel("ROC-AUC (%)", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.6)

# Save figure (optional, useful for LaTeX inclusion later)
plt.savefig("auc.png", dpi=300, bbox_inches='tight')

plt.show()